name: Gitee

on:
 push:
   branches: main

jobs:
  Gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir ~/.ssh
          cat > ~/.ssh/id_rsa <<EOF
          ${{secrets.GITEE}}
          EOF
          chmod 700 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts
          ssh -T git@gitee.com

          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com

          REPODIR=$PWD
          cd ~
          git clone git@gitee.com:oniicyan/bt_ban.git
          cd bt_ban
          cp $REPODIR/*.* ./

          git add .
          git commit -m "Update from Github Action" || exit
          git push
