name: Gitee

on:
 push:
   branches: main

jobs:
  Gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir ~/.ssh
          cat > ~/.ssh/id_rsa <<EOF
          ${{secrets.GITEE}}
          EOF
          chmod 700 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts
          ssh -T git@gitee.com

          # 请确认页面 https://gitee.com/profile/emails
          # 如勾选了 “禁止命令推送暴露个人邮箱”，请使用 @user.noreply.gitee.com 的提交邮箱
          # 如要公开邮箱，请取消勾选
          git config --local user.name ${GITHUB_ACTOR}
          git config --local user.email ${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com

          cd ~
          git clone git@gitee.com:oniicyan/bt_ban.git
          cd bt_ban

          DIR=${{github.action_path}}
          # cp ${REPODIR}/*.* ./
          ls $DIR/*.*

          # git add .
          # git commit -m "Update from Github Action"
          # git push

          # git remote add gitee git@gitee.com:oniicyan/bt_ban.git
          # git pull --rabase gitee master
          # git add ./bt_ban
          # git commit -m "Update from Github Action" || true
          # git push -f gitee master
