on:
 push:
   branches:
     - main

jobs:
 Pages:
   runs-on: ubuntu-latest
   steps:
     - env:
         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
       run: |
         git clone https://github.com/Oniicyan/Pages
         git add IPLIST.zip
         git commit -m "Update IPLIST.txt"
         git remote add target https://github.com/Oniicyan/Pages
         git push target main
