on:
 push:
   branches:
     - main

jobs:
 Pages:
   runs-on: ubuntu-latest
   steps:
     - run : |
         echo ${{ secrets.ACTION }} > ~/.ssh/id_rsa
         chmod 400 ~/.ssh/id_rsa
         ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
     - uses: actions/checkout@v4
     - run: |
         git add IPLIST.zip
         git commit -m "Update IPLIST Archive"
         git remote add target https://github.com/Oniicyan/Pages
         git push target
