on:
 push:
   branches:
     - main

jobs:
 Pages:
   runs-on: ubuntu-latest
   steps:
     - name: Set Key
       run: |
         mkdir ~/.ssh
         cat > ~/.ssh/id_rsa <<EOF
         ${{ secrets.ACTION }}
         EOF
         #chmod 400 ~/.ssh/id_rsa
         #ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
         git config --global user.name "${GITHUB_ACTOR}"
         git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"

     - uses: actions/checkout@v4

     - name: Push to another repository
       run: |
         git clone git@github.com:Oniicyan/Pages
         #git remote add git@github.com:Oniicyan/Pages
         #git add IPLIST.zip
         #git commit -m "Update IPLIST Archive" || true
         #git push target
