on:
 push:
   branches: main
 schedule:
 - cron: 55 * * * *
jobs:
 IPLIST:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - run: |
         curl -Ls https://raw.githubusercontent.com/PBH-BTN/BTN-Collected-Rules/main/combine/all.txt | sed '/#/d' | tr '\n' ',' > IPLIST.txt
         zip -r IPLIST.zip IPLIST.txt
         git add IPLIST.txt
         git commit -m "Update IPLIST.txt" || exit 0
         git add IPLIST.zip
         git commit -m "Update IPLIST Archive"
         git config --global user.name ${GITHUB_ACTOR}
         git config --global user.email ${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com
         git push
